### PR TITLE
Add ev3dev2 binding for compass calibration.

### PR DESCRIPTION
**Pull request by glipR**

### CODE REVIEW

**Comment by glipR** [comment]
This isn't actually the same functionality as IRL but its more intuitive/useful.

**Review by jtbui20 — APPROVED** [review]
Was thinking more that the global rotation would be randomized on launch, but it would be a bit extreme for weaker teams. This should be fine.

**Comment by peter-drew** [comment]
What we will probably do is create a preset option for a more difficult mode, where the sensors are less reliable/ more closely mimic real world. So we can revisit this as part of that.

**Comment by glipR** [comment]
These seem like two separate problems:
* The starting calibration of the sensors should be randomised, to force students to calibrate the compass sensors on spawn. (This isn't harder, because team No2 will need to calibrate compass sensors anyways)
* The compass sensors when calibrated shouldn't align straight to the robot, it should have some bias. (Hard sensor mode)

**Pull request merged**
