### PR TITLE
Multiprocess batch

### PR DESCRIPTION
**Pull request by glipR**
Uses multiprocessing to synchronise bot data with simulation.

Seems to run faster, and also seems to fix problems with sensor values being very late to update.

TODO:

- [x] Port robot communications (CommServer/Client)

This looks promising though!

### CODE REVIEW

**Comment by glipR** [comment]
Comparing it with 4 bots against main, it seems slightly faster, but I'm more happy that this solution is:

* MUCH simpler than the grpc solution.
* Is less likely to leave a thread behind when there is vary little computation resources available (Which seems to be catastrophic for the simulation atm).
* Gives more structure to the communications code.

**Comment by peter-drew** [comment]
Does this resolve either #177 or #115?

**Comment by glipR** [comment]
I believe it does indeed:
fixes #177 
fixes #115 

I'll need to contact Faaez and see if it works for him.

**Comment by glipR** [comment]
Also, since we are making breaking changes to how the sim is run, I think we should redesign the batch/preset/config system because at the moment tying the actual soccer field definition with particular settings is bad.

Along the same lines, we could fix #135 and #140, and possibly call this a v2 release.

**Comment by peter-drew** [comment]
I think making this a v2 release could be a good idea - although we will want to wait until after the sim competition before we release it publicly

**Comment by glipR** [comment]
Robot comms working on the demo code.

**Comment by glipR** [comment]
Note this is now merging into a v2 branch - will probably make a few PRs to that then we can PR v2 into main.

**Comment by glipR** [comment]
Tested with Faaez - does fix #115 .

**Comment by glipR** [comment]
Going to merge into v2 since I kinda need it for other changes and can fix bugs in that branch if they show up.

**Pull request merged**
