### PR TITLE
Trigger pypi release from push to release branch

### LINKED ISSUE #134: Fix deploy to pip action firing when undesired
Is firing even before a tag has been created. Think will move to branch based deploy using a protected release branch. Can still tag the releases in that branch, but won't use the tag as a trigger for the release to Pip.

Thoughts @Dalordish ?

### PR DESCRIPTION
**Pull request by peter-drew**
Closes #134

### CODE REVIEW

**Comment by glipR** [comment]
What is release process now? Create tag, merge main into release?

**Comment by peter-drew** [comment]
> What is release process now? Create tag, merge main into release?

Merging into release will trigger the pypi action, regardless of whether a tag is created (but the version number will need to be updated in the code). The tags are useful reference in the versioning so we probably want to keep them. We could make the tags on either the release or main branch, but given we have been making them on main previously should probably continue that.

**Comment by Dalordish** [comment]
I'm not sure why the "on tag create: -v" is triggering when it shouldn't be - maybe we can have a look at using the on release trigger instead and see if the change in hook will fix it? I'll have a look at that today i suppose

I'd prefer to avoid adding a third step in release (bump version, push to prod branch, tag) - if possible. If github actions is just broken then well, there's not much we can do other than use a dedicated branch

**Comment by peter-drew** [comment]
> maybe we can have a look at using the on release trigger instead and see if the change in hook will fix it? I'll have a look at that today i suppose

If you could that would be great

> I'd prefer to avoid adding a third step in release (bump version, push to prod branch, tag) - if possible. If github actions is just broken then well, there's not much we can do other than use a dedicated branch

Agreed and yes

> I'm pretty sure tags refer to a commit hash and are independant of branch

Yes. But the commits will be different because when you merge into the release branch that is a commit.

**Comment by Dalordish** [comment]
After testing in a private repo, the hook
```
on:
  release:
    types: [released]
```
works great!

Did we have any requirements on restricting releases to a certain branch? I can't remember how that discussion panned out @peter-drew

**Comment by peter-drew** [comment]
> Did we have any requirements on restricting releases to a certain branch?

Is it possible to restrict to main?

**Pull request closed without merging**
