### PR TITLE
Randomisation

### PR DESCRIPTION
**Pull request by glipR**
Addresses https://github.com/MelbourneHighSchoolRobotics/ev3sim/issues/78

- [x] Global and Device specific randomisation
- [x] Motor randomisation
- [x] Color randomisation
- [x] Ultrasonic randomisation
- [x] Compass randomisation
- [x] IR randomisation
- [x] Field randomisation
- [x] Documentation
- [x] Feasability testing

### CODE REVIEW

**Comment by glipR** [comment]
Note for future reviews - I'd recommend viewing this diff commit by commit, as while there will be a lot of stuff changed, it should be nicely separated into infrastructure for randomisation, or focusing on a particular device.

**Comment by glipR** [comment]
Pulling this out of draft because the functionality is here. Ready for some testing.

By default a lot of this stuff is disable, so safe to merge with all the year nines (sensor randomisation is tied to a flag in `ev3sim` command)

I'm not 100% on Ultrasonic and IR randomisation currently, so feel free to suggest new ways to randomise those. Pretty happy with how the others turned out.

I reckon if everything seems reasonable we can merge, release and then get feedback from yr10+ to see what they think needs to be nerfed/buffed so that all sensors are useful.

**Comment by Dalordish** [comment]
I expect I'll have some time to look over this on saturday :)

**Comment by peter-drew** [comment]
Probably want to merge this after #94 so can implement using presets rather than flags

**Comment by glipR** [comment]
Now implemented using presets, and each device is completely configurable from those presets as well.

**Comment by Dalordish** [comment]
Merging main (1.3) seems to have broken this build. Running 

```
ev3sim bot.yaml
```
results in the unhandled error:

```
An error occurred in the Simulation thread. Raising an error now...
Traceback (most recent call last):
  File "/home/dalordish/.local/bin/ev3sim", line 8, in <module>
    sys.exit(main())
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/sim.py", line 60, in main
    single_run(args.preset, args.robots, args.bind_addr, args.seed)
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/single_run.py", line 69, in single_run
    raise r[1]
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/single_run.py", line 40, in run
    runFromConfig(config, shared_data)
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/simulation/loader.py", line 167, in runFromConfig
    sl.simulate()
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/simulation/loader.py", line 87, in simulate
    interactor.startUp()
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/presets/soccer.py", line 126, in startUp
    robot.robot_class.onSpawn()
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/robot.py", line 153, in onSpawn
    self._interactor.initialiseDevices()
  File "/home/dalordish/.local/lib/python3.8/site-packages/ev3sim/robot.py", line 83, in initialiseDevices
    interactor.device_class.generateBias()
AttributeError: 'Button' object has no attribute 'generateBias'
```

**Comment by glipR** [comment]
Thanks for spotting that, should be fixed now. Wasn't an error on main branch because `generateBias` was added in this PR. I've just left the method empty (Unless we want some randomisation on our buttons?? :D)

**Comment by Dalordish** [comment]
I haven't had a chance to go through each device yet, but looking into some things like motors and IR, this works *really* well.

**Comment by glipR** [comment]
Not time sensitive but any other thoughts @peter-drew @Dalordish or is it big green button time :D

**Comment by peter-drew** [comment]
I'll have a bit of time to look at this in more detail tomorrow

**Comment by peter-drew** [comment]
@glipR will need to merge main in and make any updates now that the new batched_command changes have been merged.

Also need to decide what settings we are going to use as default in soccer_random for the competition.

**Comment by glipR** [comment]
@peter-drew merging seems fine. Are any devices particularly way too random / not random enough? I think it'd be good to be able to demo this this afternoon as well, so might just be best to let students decide what is and isn't possible with the current configuration. (We'll also be talking about the 6 sensors + opt in for year 10s)

**Review by Dalordish — APPROVED** [review]

**Pull request merged**
