### PR TITLE
Bot workspace change

### LINKED ISSUE #212: Reorder workspace format
Allow robot code to be sectioned off within folders for individual bots (And enforce this when linking code to bots).

### PR DESCRIPTION
**Pull request by glipR**
Fixes #212 

Makes the simulator use the new workspace standard.

TODO:
Make it so that the sim automatically detects old bot versions, and alerts the user, converts the bot into new format (This will break bots with existing relative imports but meh)

### CODE REVIEW

**Comment by glipR** [comment]
Very happy with how this turned out.
Updating should automatically convert bot and preset files as needed, and new format is much simpler and accessible. If the robocup people haven't started testing they should definitely use this version instead.

Thanks for the input @angustrau @peter-drew

**Comment by glipR** [comment]
Tested locally with exe and command line usage.

**Comment by peter-drew** [comment]
Realised I missed this one, will review now

**Comment by glipR** [comment]
Back on latest main @peter-drew .

**Review by peter-drew — APPROVED** [review]

**Pull request merged**
