### PR TITLE
Compass randomisation

### LINKED ISSUE #148: Add random noise to Compass sensor

### PR DESCRIPTION
**Pull request by glipR**
Fixes #148.

Pretty happy with the way this works, offset slowly creeps up with a few patterns specified by the particular device. Calibrating resets this offset.

At the moment the amount of creeping offset is pretty tame but can increase if you want @peter-drew . Keep in mind that in some cases this could just creep completely off of the actual value, just like real compasses :D

### CODE REVIEW

**Comment by peter-drew** [comment]
This looks good, but I'm not sure how much the compasses drift during a game. I think rather the error has three components:
- A fixed offset throughout the entire game, but this is handled by calibration so can be ignored
- The non linear nature of the compass, which is handled by the points variance
- Random noise, added on last, which is basically static

Is it possible to adjust parameters to better match the last characteristic? I am worried if we make the compass too noisy we will make the challenge too hard.

**Comment by peter-drew** [comment]
Testings suggests that over 5 minutes the compass drifts over 90 degrees, which is probably too much. Teams could recalibrate every time a goal is scored, but probably too much to ask given the time frame.

**Review by peter-drew — CHANGES_REQUESTED** [review]
Remove or reduce drift

**Comment by glipR** [comment]
Fair enough, I do like this travelling bias whoever, so I'll just clamp it between -15 and 15 degrees. Hopefully that is close enough for what you're expecting.

**Review by peter-drew — APPROVED** [review]

**Comment by peter-drew** [comment]
This looks good

**Pull request merged**
