### PR TITLE
Sim ux change

### PR DESCRIPTION
**Pull request by glipR**
Removes user defined sim files. Moves soccer and rescue to the main screen. Some more user-proofing when it comes to selecting bots for sims.

### CODE REVIEW

**Comment by glipR** [comment]
This is probably the biggest change when it comes to sim usability. Can already tell this will be much easier.

**Comment by glipR** [comment]
lmk if this is kind of the idea you also had for the menus @jtbui20 . Still also need to redesign the bot picker as it currently isn't great / requires more clicks than it should.

**Comment by jtbui20** [comment]
That's mainly in line with what I have on my draft, but I'm probably looking to condense the options / bot select screens into one.
I feel like an immediate quick start doesn't feel right (going straight from home -> field) unless there would only be one combination of robots that a person would use. Going from home -> options + bots -> field) with a quick way to go to the field would be preferable as a means of a "confirmation message" that yes, you do want these bots and yes, these are the right rules. E.g. on keyboard controls you'd just "mash space", similar to mashing next on installation prompts and whatnot; there's an opportunity to double check but if you REALLY don't mind then you'd just move on quickly.

**Comment by glipR** [comment]
Fair enough, I had that in mind too but didn't want to overhaul the settings and bot select page just yet.

The settings themselves aren't too important and so can probably scroll below the bot selection page, I don't think its wise to try to fit them all on screen at once. Either that or a tab at the top to switch between settings and bot selection (With bot selection being the default landing tab)

**Comment by glipR** [comment]
(Fixes #210)

**Review by peter-drew — APPROVED** [review]
This is a lot better

**Pull request merged**
