### PR TITLE
Remove Admin privileges to ev3sim.exe

### PR DESCRIPTION
**Pull request by glipR**
Removes that annoying prompt on open and is good all round.

Has been tested in updating and a fresh install locally, although testing from school computers from other users would be appreciated.

### CODE REVIEW

**Comment by glipR** [comment]
https://mhsviceduau.sharepoint.com/:u:/s/roboticsclubadmin/ES3TK0Mhvi9GtKbeNqBoJzoBdsKtyY2Nzkk7PpFedE95fw?e=0FZw02

If you want the exe from this build

**Comment by glipR** [comment]
@peter-drew Can you have a play around with this before Thursday if you want a no-admin build before next release?

**Comment by peter-drew** [comment]
> Can you have a play around with this before Thursday if you want a no-admin build for next release?

Can do

**Comment by glipR** [comment]
Want to build on my PC to avoid errors and we can always ask ppl to downgrade if it turns out the school computers don't like this change. Merging for now.

**Pull request merged**
