### PR TITLE
Batched commands

### PR DESCRIPTION
**Pull request by glipR**

### CODE REVIEW

**Comment by glipR** [comment]
This adds the ability to run the simulator, with bots/preset and attach code from a single command.

The documentation on how to use this, as well as its shortcomings is an artifact of this build: https://github.com/MelbourneHighSchoolRobotics/ev3sim/pull/53/checks?check_run_id=1039642039

I've also bumped the version number since we'll release once this is merged.

**Comment by angustrau** [comment]
Perhaps the [multiprocessing](https://docs.python.org/3.4/library/multiprocessing.html) library can provide a more stable way to start the attached processes

**Comment by glipR** [comment]
> 
> 
> This assumes that ev3attach exists in the path. Perhaps the [multiprocessing](https://docs.python.org/3.4/library/multiprocessing.html) library can provide a more stable way to start the attached processes

Originally tried `threading` as we've done with existing communications changes, with about the same success as these changes. This command should only be run when `ev3attach` is in the path anyways, to my knowledge (since it's invoked with ev3sim). If you think multiprocessing is worthwhile then open to some modifications to this PR.

**Comment by glipR** [comment]
Now uses multiprocessing @angustrau , lmk if I'm doing anything in a bad way.

Good call though, seems much more stable and output gets piped much more reliably to the main thread.

**Review by peter-drew — APPROVED** [review]

**Review by angustrau — APPROVED** [review]

**Pull request merged**
