### PR TITLE
Console input

### PR DESCRIPTION
**Pull request by glipR**
Allows console input to be requested / given through the simulator.

Should not have a text entry open unless a program is requesting input, and combined with #246 the input message wouldn't be removed.

This doesn't particularly work well with multiple robots atm, but I don't think it really needs to. More just including this because it makes introductory workshops a lot smoother (and cooler).

### CODE REVIEW

**Comment by glipR** [comment]
Hmm, I think I've got a way where we can support multiple bots requesting input in a reasonable manner, might come back to this tomorrow.

**Comment by glipR** [comment]
Is now easy for multiple bots to request input, and for interactors to request input / fill input.

After #246 is merged should probably also make it so that input messages aren't removed until their input is received.

**Comment by glipR** [comment]
Needs to be combined with #246 into a single PR, as both change console functionality.

**Comment by glipR** [comment]
Happy with this now. Works in the following way:

* Robots can request input
* Interactors (Such as custom tasks and soccer) can request input
* Interactors can post input (to robots)
* Cleans messages up nicely on reset
* Additionally, if there are no permanent messages in console, then keep the last temporary message alive (No point fading it out)

**Review by angustrau — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
