### PR TITLE
WIP: Add rescue

### PR DESCRIPTION
**Pull request by glipR**
Currently supports dynamically loading rescue tile presets into the space, and has a minimal ui.

- [x] Add all normal rescue tiles.
- [x] Add some UI elements to show penalties, tiles completed.
- [x] Add ability to click to spawn a bot at a specific tile (Not the same as dragging).
- [x] Add water tower, tunnel (Just two static poles).
- [x] Add ramps (Fake by adding extra directional friction on locations?).
- [x] Add end goal, can placement judge.
- [x] ~Add support for motors to be used to modify rotation on hinge joints. (Claws)~ This seems impossible in pymunk, joints are supposed to be disjoint.
- [x] More judge support.
- [ ] Finishing touches.
- [x] Tileset editor, tied to batch.

This might be a good pull request to encourage students to contribute to if they want to mess around with the system, as there's a lot of somewhat simple tasks, that require you to understand the design of presets as well as what the simulator has access to.

### CODE REVIEW

**Comment by glipR** [comment]
rescue

Some nice progress on a UI/Judge. Still need to add shortcuts to the follow points,

**Comment by glipR** [comment]
@peter-drew do we have any better resources to base the rescue tiles off of? The best I could find was this image:
https://www.robocupjunior.org.au/sites/default/files/Rescue/rescuefield.jpg

Also, because of the license we have are we going to be able to use designs similar to that in the MTA sets?

**Comment by peter-drew** [comment]
@glipR Not sure about the license, can ask Evan and see who owns the designs. We do have more detailed designs, in the OneDrive.

**Comment by peter-drew** [comment]
The UI and judge is looking amazing!

**Comment by glipR** [comment]
Back on main now, so many conflicts T_T

**Comment by glipR** [comment]
Adding some more tiles has really started bringing this together:
image

Need some way to highlight which of the tiles the buttons on the left correspond to, might try highlighting the tile on hover or something.

**Comment by glipR** [comment]
Also we could totally make some wacky tiles for a fun competition that you wouldn't normally be able to do IRL, might make for a more programmatically interest rescue comp.

**Comment by peter-drew** [comment]
This is looking amazing, really coming together.

> Need some way to highlight which of the tiles the buttons on the left correspond to, might try highlighting the tile on hover or something.

Would it be possible to number the tiles, perhaps in the bottom corner (but invisible to the colour sensors)? Or perhaps name them somehow, but wouldn't work when duplicates.

**Comment by glipR** [comment]
Numbering is a good call yeah, I think pygame adds some support for masking too so might try that.

**Comment by glipR** [comment]
Some TODOs for another time:

- [ ] Add a few more tiles of just normal turns
- [ ] Redo some of checkpoint/completion code. Requiring getting the final few points / first few points.
- [ ] Rescue sim: can mode vs follow mode (Safely swap between the two on tile completion and bot spawn)
- [ ] Batch creation: dialog to select soccer or rescue
- [ ] Hover tile red outline when simulating.

**Comment by glipR** [comment]
OK, all functionality I wanted is done, some of the implementation is a bit iffy and ui needs some heavy improvement, but as with the gui changes, its good enough for now :)

Going to merge!

**Pull request merged**
