### PR TITLE
Bug window move

### LINKED ISSUE #55: Dragging pygame window kills ongoing `attach` scripts, if waiting on data.
Because dragging the pygame window pauses execution on that thread, no tick update data is sent which causes `Simulation Died` in the communications threads, if waiting for a send/recv.

Unsure what the best way to fix this is.

### PR DESCRIPTION
**Pull request by glipR**
Fixes #55 .

Was a lat more painful than I was expecting, turns out that the attach script was also silently raises a Deadline exception, which needed to be handled separately.

Also added support for dynamic resizing of the window, which while technically functional doesn't handle a few of the objects in our soccer preset to nicely (Try it out for yourself to get an idea of this)

### CODE REVIEW

**Review by Dalordish — APPROVED** [review]
Very nice! We'll probably want to fix the funky behaviour with resizing at some point, but even having it there is good because it means people running into the issue where the pygame window is larger than their screen have another option.

**Comment by glipR** [comment]
Actually I might keep this PR open for a bit and add some extra changes, so that font size and image size scales with the difference between the starting screen size and the current screen size. This should be the only 2 things stopping the window from being completely responsive from what I can tell.

**Comment by glipR** [comment]
resize
😎 

@Dalordish lmk if u spot anything out of order, otherwise will merge.

**Comment by Dalordish** [comment]
Seems fine!

**Pull request merged**
