### PR TITLE
Green box

### LINKED ISSUE #169: Make colour sensor read green when in penalty box
The penalty box of the actual field is green, so the actual colour red should be green, so want the colour read to be green, like the behaviour for th goals.

### PR DESCRIPTION
**Pull request by glipR**
Fixes #169 .

The colour sensor sees a green patch below the grey box. Alternatively we can keep the penalty box green.

### CODE REVIEW

**Review by peter-drew — DISMISSED** [review]

**Review by peter-drew — CHANGES_REQUESTED** [review]
Appears to break the goal score highlighting

**Comment by glipR** [comment]
Do we want the goal highlighting btw? I was kinda confused that colour sensor was returning white when hovering around it which is why I changed it. Happy to revert just want to make sure its the best option.

**Comment by peter-drew** [comment]
> Do we want the goal highlighting btw?

I think so, or at least to have the option like there was before. It can be hard to tell when a goal has been scored without it. Is it possible to add transparency, say 50%, so people can see what is underneath? Although that may look hideous.

**Comment by glipR** [comment]
To my knowledge not without rewriting a fair amount of the visual system - pygame transparency is pretty limited. Just going to revert the changes.

**Review by peter-drew — CHANGES_REQUESTED** [review]
Thanks for adjusting that. Although it appears the ball is invisible now.

**Comment by glipR** [comment]
Hahaha don't know how I missed that. That'd be a pretty botched release :/

**Review by peter-drew — APPROVED** [review]

**Pull request merged**
