### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by glipR**
Required / Easy changes
- [x] Remove threading, #115 
- [x] #140 
- [x] #135 
- [x] #181
- [x] #183
- [x] Many many documentations

Wishlist
- [ ] #155
- [x] ~#170~ Decided against this.
- [ ] #128
- [ ] #100
- [ ] #88
- [x] #40 

=======================

Update:
I've got pretty much all the features I was hoping for/thought were reasonable in the branch now (open to suggestions however, of course)

Here's a final checkbox of things to do before this branch is safe to merge and release (stuff might be added, but adding small things as comments won't happen anymore):

## Documentation

- [x] Installation (Windows)
- [x] ~PyInstaller distributable installation (Mac/Linux)~ Not happening for now.
- [x] pip installation / usage
- [x] Object Hierarchy updated (sims, bots, presets) and simplified
- [x] Console Usage / Features
- [x] Custom preset definitions

## Executable

- [x] ~Make workflows for and test pyinstaller directories for mac and linux~ Not happening for now.
- [ ] Update installer to use new logo if available

## Cleanup

- [x] Abstract button events in all pygame_gui code.
- [x] Remove `generateObjects` and `sizeObjects`, and just define each object once. Add a method to update the theming based on state.
- [x] Remove unused imports from all files.
- [x] Review the introduced structure and see if there's a better way of going about the gui design
- [x] Simplify the preset surface (The code is currently very verbose, and making future presets is currently annoying).

## Touchup

- [ ] New logo (V happy with outside input on this).
- [x] Redesign Bot/Batch select screens (I have ideas).
- [x] ~Redesign Rescue screen (if worthwhile, maybe just change colours).~ Not happening for now.
- [x] Push requirements up where appropriate.

## System changes

- [x] Make presets able to create visuals with pygame gui (Give interactors an applyToScreen method or something)
- [x] Ultrasonics seem broken?
- [x] ~Move ScreenObjectManager methods to Sim menu where appropriate.~ Decided against this.
- [x] Extend the events system.
- [x] Fix bugs with pressing delete in edit modes.
- [x] Allow rectangular baseplates.
- [x] Fix rotation bug with devices in bot editor.

Doesn't seem like tests are going to happen, not from me at least :).

### CODE REVIEW

**Comment by glipR** [comment]
Minor TODO:
- [ ] Rectangles for bot editor
- [ ] Bot follow position for rescue bots
- [ ] Nice fading backgrounds with some splash images for title screen

**Review by glipR — COMMENTED** [review]
@angustrau Latest commit is the changes we talked about. I think I hit a nice middle ground.
You can't do `..parent` style imports, but you can import as if you are executing from essentially any parent folder, so `parent.other_code` can be imported from `parent/entry.py`.
You do however need to include `__init__.py` files in lots of places.

The upside of this however is copying a students folder into the /code/ directory now won't have any problems with imports. Now the only thing to change would be the relative path of the entrypoint in the bot definition.

**Comment by glipR** [comment]
OK, I think its time I merged this, as I'm not going to have a bunch of time for some more things that should probably be added down the line.

That being said, the following tasks remain untouched:

* Mac/Linux PyInstaller support (Not a big deal, pip method should still work, but untested)
* Robots blocking IR (Can come in a separate version if we really want)
* New logo (Would prefer this came with v2 but its not coming from me so no point waiting :p)
* LED Support (Again not a big deal, later version might add)
* Halves in soccer (Not a big deal, does not affect fairness)

Any thoughts @Dalordish @peter-drew @angustrau ? Feel free to play around or check/edit the new docs. I think for the most part its ready though.

**Comment by peter-drew** [comment]
@glipR could you please make a list of areas you would like me to focus my testing on

**Comment by glipR** [comment]
> 
> 
> @glipR could you please make a list of areas you would like me to focus my testing on

@peter-drew :

INSTALLER:

- One click installer works fine, workspace creation is prompted upon first opening the program.
- EV3Sim shows up in start menu after using the one click
- (After creating custom bots and batches) double clicking or right click actions on `.sim` and `.bot` files works as expected.

BOTS:

- Creating a bot, resizing elements, changing colours and adding devices
- Renaming a bot
- Specifying the code for a bot from the workspace folder

SIMS:

- Creating a sim (soccer or rescue)
- Renaming a sim
- Changing the sim settings and running to ensure they've taken effect

GENERAL:

- Sensors are still working as expected
- Everything looks presentable (let me know if you've got any ui improvements)
- Easy to use
- Uninstaller works. No lasting file associations (Not terrible if this doesn't happen though)

I've fixed a few bugs before last generating the .exe. I've updated the file uploaded here: https://github.com/MelbourneHighSchoolRobotics/ev3sim/releases/tag/untagged-b83fa7c7f6ea4aaa1f8d

You should download this file and use the installed application for testing. Thanks a bunch!

**Comment by peter-drew** [comment]
@glipR I get this error when I select my workspace folder on first load. Doesn't seem to stop the simulator working.

`UserWarning: Finding font with id: Poppins_italic_48 that is not already loaded.
Preload this font with {'name': 'Poppins', 'point_size': 48, 'style': 'italic'}
  warnings.warn(warning_string, UserWarning)`

**Comment by peter-drew** [comment]
Should we throw an error when no bot selected or fail gracefully?

`ev3sim\presets\rescue.py", line 464, in locateBots
    raise ValueError("No robots loaded.")
ValueError: No robots loaded.`

**Comment by peter-drew** [comment]
> when I select my workspace folder on first load.

And appears to throw this error on every subsequent load as well.

**Comment by peter-drew** [comment]
How is lack of progress in rescue determined? At least using the controllable bot, it appears that it might be too aggressive. But further testing needed.

**Comment by peter-drew** [comment]
> How is lack of progress in rescue determined? At least using the controllable bot, it appears that it might be too aggressive. But further testing needed.

See below, is possible to get the robot completely stuck, even after moved (originally got stuck in the doorway).

**Comment by peter-drew** [comment]
> How is lack of progress in rescue determined? At least using the controllable bot, it appears that it might be too aggressive. But further testing needed.

See below, is possible to get the robot completely stuck, even after moved (originally got stuck in the doorway).

**Comment by peter-drew** [comment]
Using the backspace key in the radius field of the bot editor (on a new bot) causes simulator to crash.

`ev3sim\visual\menus\bot_edit.py", line 206, in removeSelected
    raise ValueError("The remove button should not be visible at the moment.")
ValueError: The remove button should not be visible at the moment.`

**Comment by angustrau** [comment]
Crash when closing the bot script selection dialog without a file selected

```
Traceback (most recent call last):
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/venv/bin/ev3sim", line 33, in <module>
    sys.exit(load_entry_point('ev3sim', 'console_scripts', 'ev3sim')())
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/ev3sim/gui.py", line 224, in main
    raise error
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/ev3sim/gui.py", line 213, in main
    StateHandler.instance.mainLoop()
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/ev3sim/simulation/loader.py", line 347, in mainLoop
    events = ScreenObjectManager.instance.handleEvents()
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/ev3sim/visual/manager.py", line 247, in handleEvents
    self.screens[self.screen_stack[-1]].handleEvent(event)
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/ev3sim/visual/settings/menu.py", line 128, in handleEvent
    obj.handlePressed(idx - index)
  File "/home/angus/Documents/git/MHSRobotics/ev3sim/ev3sim/visual/settings/elements.py", line 157, in handlePressed
    filename = askopenfilename().replace("/", "\\")
AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by glipR** [comment]
> Crash when closing the bot script selection dialog without a file selected ...

Fixed @angustrau 




> 
> 
> Using the backspace key in the radius field of the bot editor (on a new bot) causes simulator to crash.
> 
> `ev3sim\visual\menus\bot_edit.py", line 206, in removeSelected raise ValueError("The remove button should not be visible at the moment.") ValueError: The remove button should not be visible at the moment.`

This was fixed a while back. You probably have an old version installed. Just use the .exe from https://github.com/MelbourneHighSchoolRobotics/ev3sim/releases/tag/untagged-028dedf37b832215eb1f



> 
> 
> Should we throw an error when no bot selected or fail gracefully?
> 
> `ev3sim\presets\rescue.py", line 464, in locateBots raise ValueError("No robots loaded.") ValueError: No robots loaded.`

Will do this tonight, need to add functionality for some error dialogs in generic menus.



> 
> 
> How is lack of progress in rescue determined? At least using the controllable bot, it appears that it might be too aggressive. But further testing needed.

Possibly. The getting stuck in lack of progress issue I can possibly fix, but tweaking the lack of progress stuff is probably best for 2.1. I can point you towards where these calibration constants are defined.

(@peter-drew @angustrau thanks for the comments)

**Comment by glipR** [comment]
Ok, the no bots error has also been fixed, and furthermore I've gone through and removed any other explicit `raise ValueError`s which should instead be gui error dialogs. That being said its very likely I'm assuming certain things about input, and so more errors are likely to occur.

@peter-drew lmk if you run into any more bugs. I think for now we can leave the rescue lack of progress stuff, you can always reset when this occurs.

**Comment by peter-drew** [comment]
Thanks @glipR , will take another look tomorrow.

**Comment by glipR** [comment]
The site link change looks good to me, will build and try the installer in a sec.
Going to set up some simple error logging tonight on the exe as I'm sure we'll get some bug reports, then provided you don't have any more bugs to add am happy to merge.

**Comment by peter-drew** [comment]
Haven't actually had an opportunity to look again yet, will take a look and let you know.

**Comment by glipR** [comment]
Error logging seems to work, will add a small line in the issue template to mention that this exists.

The only current outstanding thing atm it seems is the rescue thing, which I'm fine for keeping as is, at least until 2.1.

The font warning takes a bit of effort to get around and has 0 effect on the exe, as the warning is suppressed. So for now I'll ignore that too.

As for anything else I've avoided for 2.0 release and might want to revisit:
* Anything from the checkboxes at the top of the PR
* Rescue fixes
* Support randomisation through the GUI

Otherwise lmk if you run into anything @peter-drew

**Comment by peter-drew** [comment]
Got this error when editing a bot plate, can't remember specifics:
Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\gui.py", line 213, in main
    StateHandler.instance.mainLoop()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\simulation\loader.py", line 352, in mainLoop
    ScreenObjectManager.instance.applyToScreen()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\manager.py", line 231, in applyToScreen
    self.screens[self.screen_stack[-1]].draw_ui(blit_screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\menus\bot_edit.py", line 1582, in draw_ui
    ScreenObjectManager.instance.applyToScreen(to_screen=self.bot_screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\manager.py", line 228, in applyToScreen
    self.objects[key].applyToScreen(blit_screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\objects.py", line 591, in applyToScreen
    self._applyToScreenGfx(screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\objects.py", line 572, in _applyToScreenGfx
    pygame.gfxdraw.aaellipse(screen, *self.point, self.h_radius, self.v_radius, self.stroke)
OverflowError: signed short integer is greater than maximum


Got this one when putting a negative plate diameter:
Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\gui.py", line 213, in main
    StateHandler.instance.mainLoop()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\simulation\loader.py", line 352, in mainLoop
    ScreenObjectManager.instance.applyToScreen()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\manager.py", line 231, in applyToScreen
    self.screens[self.screen_stack[-1]].draw_ui(blit_screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\menus\bot_edit.py", line 1582, in draw_ui
    ScreenObjectManager.instance.applyToScreen(to_screen=self.bot_screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\manager.py", line 228, in applyToScreen
    self.objects[key].applyToScreen(blit_screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\objects.py", line 591, in applyToScreen
    self._applyToScreenGfx(screen)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\visual\objects.py", line 572, in _applyToScreenGfx
    pygame.gfxdraw.aaellipse(screen, *self.point, self.h_radius, self.v_radius, self.stroke)
pygame.error: Surface doesn't have a colorkey

**Comment by peter-drew** [comment]
Neither of these are blocking bugs

**Review by peter-drew — APPROVED** [review]
Looks good to merge, no critical bugs. I'm sure the students will find any issues.

**Comment by glipR** [comment]
Fixed both bugs you mentioned, thanks for that.
Have also made it so that the scrolling feature for values doesn't accrue small amounts (So 1.4 goes to 1.5 always, not 1.49999 or 1.500001)

Going to merge now.

**Pull request merged**
