### PR TITLE
Soccer referee

### PR DESCRIPTION
**Pull request by glipR**
some work towards #99 

Progress:
image

Currently no way to manually add penalty to bots, but everything else is configurable.

### CODE REVIEW

**Comment by peter-drew** [comment]
Getting this error using the Template Robot

```
An error occurred in the Simulation thread. Raising an error now...
Process Process-1:
Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\single_run.py", line 66, in single_run
    raise r[1]
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\single_run.py", line 37, in run
    runFromConfig(config, shared_data)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\simulation\loader.py", line 169, in runFromConfig
    sl.simulate()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\simulation\loader.py", line 115, in simulate
    self.data["data_queue"][key].put(robot._interactor.collectDeviceData())
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\robot.py", line 88, in collectDeviceData
    res[device.device_type][device._getObjName(port)] = device.toObject()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\devices\infrared\base.py", line 76, in toObject
    data[f"value{x}"] = self.value(x)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\ev3sim\devices\infrared\ev3.py", line 74, in value
    return self._predict(self._values)
AttributeError: 'InfraredSensor' object has no attribute '_values'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\peter\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\grpc\_server.py", line 875, in _serve
    if not _process_event_and_continue(state, event):
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\grpc\_server.py", line 839, in _process_event_and_continue
    rpc_state, rpc_future = _handle_call(event, state.generic_handlers,
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\grpc\_server.py", line 749, in _handle_call
    return _handle_with_method_handler(rpc_event, method_handler,
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\grpc\_server.py", line 722, in _handle_with_method_handler
    return state, _handle_unary_stream(rpc_event, state,
  File "c:\users\peter\appdata\local\programs\python\python38\lib\site-packages\grpc\_server.py", line 640, in _handle_unary_stream
    return thread_pool.submit(_stream_response_in_pool, rpc_event, state,
  File "c:\users\peter\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 179, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

**Comment by glipR** [comment]
@peter-drew This will be fixed once the randomisation PR is merged. In that I change some stuff about how devices are instantiated, causing the above error.

For now I'd wait for that to be merged, or just test this without any code running with `ev3sim bot.yaml`, and drag stuff around.

**Comment by peter-drew** [comment]
Can we merge shared_random into this branch now? Share_random is mostly done and will be merging into main in the coming days.

**Comment by peter-drew** [comment]
Looks really good so far, really nice to have the ball reset automated.

One thing I have noticed is very weird behaviour when you set either or both of 'ball_reset_on_white' or 'out_on_white' to false.

**Comment by glipR** [comment]
> Can we merge shared_random into this branch now? Share_random is mostly done and will be merging into main in the coming days.

I'd rather not, I need to do some changes after that merge and I don't want to mess with the log after merging main.

> One thing I have noticed is very weird behaviour when you set either or both of 'ball_reset_on_white' or 'out_on_white' to false.

I'll have a play around thanks for letting me know

**Comment by glipR** [comment]
Previous bug was fixed, me big dumb

**Comment by glipR** [comment]
Also, what do you think a good way to manually penalise bots would be (/is this required?) I was thinking of dragging the bot into the penalty zone would work.

**Comment by peter-drew** [comment]
> I was thinking of dragging the bot into the penalty zone would work.

I think this would work, although it probably won't be needed that often.

**Comment by peter-drew** [comment]
We probably want to wait a few seconds before teleporting the ball back in, to mimic the delay in real life. Because robots shouldn't follow the ball out, even if it goes out.

**Comment by peter-drew** [comment]
When a goal is scored, all damaged robots should reenter play.

Also, when a robot that is already in the penalty box is clicked and dragged in a second time an assertion error occurs because key UI-penalty-0 is already in use.

**Comment by glipR** [comment]
> When a goal is scored, all damaged robots should reenter play.

Good idea

> Also, when a robot that is already in the penalty box is clicked and dragged in a second time an assertion error occurs because key UI-penalty-0 is already in use.

You shouldn't be able to click/drag once they are in the box, they should be stuck in place last time I checked.

**Comment by peter-drew** [comment]
Have opened issues for things that need to currently be done on this pull request to help organise.

Namely: #144 #145 #146 #147

**Comment by glipR** [comment]
Now resolves #144, #145, #146, #147 🔥 ⌚

**Comment by peter-drew** [comment]
Closes #144, #145, #146, #147

**Review by peter-drew — APPROVED** [review]

**Comment by glipR** [comment]
I can't approve my own PR but happy with the changes you made @peter-drew , thanks for the clarity changes - I really haven't been making sure my code makes sense given the time frame :D

Happy for a bump in version no. + Merge.

**Comment by peter-drew** [comment]
Yep. Let's merge #149 first.

**Review by platy11 — APPROVED** [review]

**Pull request merged**
