### PR TITLE
Adjust constants

### LINKED ISSUE #85: Evaluate rotational speed and acceleration constants
Possibly too fast at the moment

### PR DESCRIPTION
**Pull request by peter-drew**
Closes #85

### CODE REVIEW

**Comment by glipR** [comment]
looks good to me locally, does seem slow but I only really remember the orange balls so that might be why :)

**Review by glipR — DISMISSED** [review]

**Comment by peter-drew** [comment]
It is quite a large shift, although for memory the ball wouldn't bounce across the table more than once.

**Comment by peter-drew** [comment]
Will request a few further reviews

**Comment by glipR** [comment]
Didn't notice is was 1, so no friction hahaha. This seems better yep.

**Review by glipR — APPROVED** [review]

**Pull request merged**
