### PR TITLE
Disable drag / drop for controls

### PR DESCRIPTION
**Pull request by jtbui20**

### CODE REVIEW

**Comment by glipR** [comment]
Could've sworn I did this on the previous PR woops. Thanks.

**Comment by jtbui20** [comment]
image
Oh noes, collider masks will be a big focus now.
Side note: ball velocity no longer resets to 0 upon goal in some circumstances. I'll try and properly reproduce it.

**Comment by glipR** [comment]
Haha good point, its not just the pause/play we don't want to move.

I'll play around with the masks.

**Comment by glipR** [comment]
Going to close this since it is superseded by changes in https://github.com/MelbourneHighSchoolRobotics/ev3sim/pull/34.

**Pull request closed without merging**
