### PR TITLE
Fix controllable

### PR DESCRIPTION
**Pull request by OwenFeik**
See issue #161

### CODE REVIEW

**Comment by OwenFeik** [comment]
Oh my mistake; this is upstream from the `gfxdraw` branch rather than main.

**Comment by glipR** [comment]
Going to wait for a PR on main before merging, I can create a new commit/PR and add you as coauthor if you're busy.

**Comment by OwenFeik** [comment]
That would be great thanks.

**Comment by glipR** [comment]
Oh nvm github merge to main is smart. Thanks @peter-drew

**Review by glipR — APPROVED** [review]

**Pull request merged**
